### ISSUE TITLE
Can't show page before it's fully loaded

### ISSUE THREAD

**Issue by L-as** [nihilowy/surfer#27]
Currently it seems like it waits for all resources to finish loading before showing the page. This makes it e.g. take ages when accessing wikipedia.org, which really should not take that long to show. Perhaps there could be some configuration option to make it show the page instantly without waiting for the assets to load?

**Comment by nihilowy** [comment]
done in config.h , hope it works.

**Comment by L-as** [comment]
It doesn't work unfortunately. I set `#define DONT_WAIT_FOR_SITE_FULLLOAD` and https://wikipedia.org still shows nothing until it's fully loaded, which takes a very long time.

**Comment by nihilowy** [comment]
honestly I dont know, i remember it was workin before I added this signal . maybe test firefox / other . disable images  or so. I cant help You.
